run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

  revive:
    min-confidence: 0.8
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true
      - name: unused-parameter
        disabled: true

  gocyclo:
    min-complexity: 25

  dupl:
    threshold: 150

  goconst:
    min-len: 3
    min-occurrences: 5

  misspell:
    locale: US

  lll:
    line-length: 250

  goimports:
    local-prefixes: github.com/piotrlaczkowski/GoLangGraph

  funlen:
    lines: 150
    statements: 80

  gocognit:
    min-complexity: 30

  nestif:
    min-complexity: 6

  gomnd:
    checks: argument,case,condition,operation,return,assign
    ignored-numbers: 0,1,2,3,4,5,10,100,1000

  godox:
    keywords:
      - FIXME
      - BUG

  dogsled:
    max-blank-identifiers: 2

  whitespace:
    multi-if: false
    multi-func: false

  godot:
    scope: declarations
    capital: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - unused
    - errcheck
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

issues:
  uniq-by-line: true
  exclude-dirs:
    - examples/
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - unparam
        - stylecheck
        - errcheck
        - gosec
        - dupl
        - noctx
        - staticcheck
        - revive

    - path: examples/
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - errcheck
        - unparam
        - stylecheck
        - gosec
        - dupl
        - revive

    - path: cmd/
      linters:
        - gomnd
        - funlen
        - unparam
        - stylecheck
        - gochecknoinits
        - errcheck
        - gosec
        - revive

    - linters:
        - lll
      source: "^//go:generate "

    - linters:
        - govet
      text: "fieldalignment:"

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - staticcheck
      text: "SA5011:"

    - linters:
        - staticcheck
      text: "SA9005:"

    - linters:
        - unused
      text: "is unused"
      path: _test\.go

    - linters:
        - unused
      text: "field.*is unused"

    - linters:
        - stylecheck
      text: "ST1005:"

    - linters:
        - stylecheck
      text: "ST1000:"

    - linters:
        - stylecheck
      text: "ST1020:"

    - linters:
        - revive
      text: "package-comments:"

    - linters:
        - revive
      text: "exported:"

    - linters:
        - revive
      text: "unused-parameter:"

    - linters:
        - unparam
      text: "is unused"
      path: "cmd/"

    - linters:
        - unparam
      text: "is unused"
      source: "func.*\\(.*\\).*{$"

    - linters:
        - errcheck
      source: "defer.*\\.(Close|Unlock)\\(\\)"

    - linters:
        - errcheck
      source: "\\.(SetStartNode|AddEndNode|Execute|RegisterTool|RegisterProvider|WriteJSON|Encode)\\("

    - linters:
        - gosec
      text: "G301:|G306:|G304:|G204:|G104:|G302:"

    - linters:
        - rowserrcheck
      text: "rows.Err must be checked"

    - linters:
        - misspell
      text: "cancelled.*canceled"

    - linters:
        - whitespace
      text: "unnecessary leading newline"

    - linters:
        - noctx
      path: _test\.go
