groups:
  - name: go-agents-alerts
    rules:
      # Service Health Alerts
      - alert: ServiceDown
        expr: up{job="go-agents-simple"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Go-Agents service is down"
          description: "The Go-Agents application has been down for more than 30 seconds"

      # Performance Alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="go-agents-simple"}[5m])) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 2 minutes"

      - alert: HighErrorRate
        expr: rate(http_requests_total{job="go-agents-simple",code!="200"}[5m]) / rate(http_requests_total{job="go-agents-simple"}[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for more than 1 minute"

      # Resource Alerts
      - alert: HighMemoryUsage
        expr: (go_memstats_alloc_bytes{job="go-agents-simple"} / go_memstats_sys_bytes{job="go-agents-simple"}) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} for more than 5 minutes"

      - alert: HighGoroutines
        expr: go_goroutines{job="go-agents-simple"} > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of goroutines"
          description: "Number of goroutines is {{ $value }} for more than 5 minutes"

      # Agent-specific Alerts
      - alert: AgentHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=~"/api/.*"}[5m])) > 10
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "Agent {{ $labels.handler }} has high latency"
          description: "Agent {{ $labels.handler }} 95th percentile latency is {{ $value }}s"

      - alert: AgentErrors
        expr: increase(http_requests_total{handler=~"/api/.*",code!="200"}[5m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Agent {{ $labels.handler }} has errors"
          description: "Agent {{ $labels.handler }} had {{ $value }} errors in the last 5 minutes"

  - name: infrastructure-alerts
    rules:
      # System Resource Alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanizePercentage }} for more than 5 minutes"

      - alert: HighMemoryUsageSystem
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | humanizePercentage }} for more than 5 minutes"

      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is {{ $value | humanizePercentage }} for more than 5 minutes"

      - alert: HighLoadAverage
        expr: node_load15 > 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High load average on {{ $labels.instance }}"
          description: "15-minute load average is {{ $value }} for more than 10 minutes"
